import { type Kysely, sql } from 'kysely';

const BY_DEFAULT_TABLES = ['species', 'moves', 'abilities', 'items', 'types'] as const;
const ALWAYS_TABLES = ['forms'] as const;

export async function up(db: Kysely<any>): Promise<void> {
  for (const table of BY_DEFAULT_TABLES) {
    await sql`ALTER TABLE ${sql.ref(table)} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`.execute(
      db
    );
    await sql`SELECT setval(pg_get_serial_sequence(${table}, 'id'), COALESCE((SELECT MAX(id) FROM ${sql.ref(table)}), 1), (SELECT EXISTS(SELECT 1 FROM ${sql.ref(table)})))`.execute(
      db
    );
  }

  for (const table of ALWAYS_TABLES) {
    await sql`ALTER TABLE ${sql.ref(table)} ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY`.execute(
      db
    );
    await sql`SELECT setval(pg_get_serial_sequence(${table}, 'id'), COALESCE((SELECT MAX(id) FROM ${sql.ref(table)}), 1), (SELECT EXISTS(SELECT 1 FROM ${sql.ref(table)})))`.execute(
      db
    );
  }
}

export async function down(db: Kysely<any>): Promise<void> {
  for (const table of [...BY_DEFAULT_TABLES, ...ALWAYS_TABLES]) {
    await sql`ALTER TABLE ${sql.ref(table)} ALTER COLUMN id DROP IDENTITY IF EXISTS`.execute(db);
  }
}
