/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type ImageStatus = 'deleted' | 'pending_published' | 'pending_upload' | 'published';

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Abilities {
  desc: string | null;
  id: number;
  name: string;
  short_desc: string | null;
  slug: string;
}

export interface AbilityFlags {
  ability_id: number;
  flag_id: number;
}

export interface AbilityFlagTypes {
  description: string | null;
  id: number;
  name: string;
  slug: string;
}

export interface AbilitySlots {
  id: number;
  name: string;
  slug: string;
}

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface ArticleCategories {
  description: string | null;
  id: Generated<number>;
  name: string;
  slug: string;
}

export interface ArticleCategoryMap {
  article_id: number;
  category_id: number;
}

export interface ArticleImages {
  article_id: number;
  created_at: Generated<Timestamp>;
  image_id: string;
  is_cover: Generated<boolean>;
  sort_order: Generated<number>;
}

export interface Articles {
  body: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  owner_id: string | null;
  slug: string;
  subtitle: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface AspectChoices {
  aspect_id: number;
  aspect_string: string | null;
  id: number;
  name: string;
  slug: string;
  value: string;
}

export interface AspectGroups {
  description: string | null;
  id: number;
  name: string;
  rule: string;
  slug: string;
}

export interface AspectGroupsMap {
  aspect_group_id: number;
  aspect_id: number;
}

export interface Aspects {
  aspect_format: string | null;
  id: number;
  name: string;
  slug: string;
  type_id: number;
}

export interface AspectTypes {
  id: number;
  name: string;
  slug: string;
}

export interface Behaviour {
  data: Json;
  form_id: number;
}

export interface Biomes {
  id: number;
  name: string;
  namespace_id: number | null;
  slug: string;
}

export interface BiomeTagBiomes {
  biome_id: number;
  biome_tag_id: number;
}

export interface BiomeTags {
  id: number;
  name: string;
  namespace_id: number | null;
  slug: string;
}

export interface Conditions {
  description: string | null;
  id: number;
  name: string;
  slug: string;
  type_id: number;
}

export interface ConditionTypes {
  id: number;
  name: string;
  slug: string;
}

export interface DropPercentages {
  form_id: number;
  item_id: number;
  percentage: number;
}

export interface DropRanges {
  form_id: number;
  id: Generated<number>;
  item_id: number;
  quantity_max: number;
  quantity_min: number;
}

export interface EggGroups {
  id: number;
  name: string;
  slug: string;
}

export interface ExperienceGroups {
  formula: string;
  id: number;
  name: string;
  slug: string;
}

export interface FormAbilities {
  ability_id: number;
  form_id: number;
  slot_id: number;
}

export interface FormAspectComboAspects {
  aspect_id: number;
  combo_id: number;
}

export interface FormAspectCombos {
  combo_index: number;
  form_id: number;
  id: Generated<number>;
}

export interface FormAspects {
  aspect_choice_id: number;
  form_id: number;
}

export interface FormDrops {
  amount: number;
  form_id: number;
}

export interface FormHitboxes {
  fixed: Generated<boolean>;
  form_id: number;
  height: number;
  width: number;
}

export interface FormImages {
  created_at: Generated<Timestamp>;
  form_id: number;
  image_id: string;
  is_primary: Generated<boolean>;
  sort_order: Generated<number>;
}

export interface FormLabels {
  form_id: number;
  label_id: number;
}

export interface FormMoves {
  form_id: number;
  level: number | null;
  method_id: number;
  move_id: number;
}

export interface FormOverrideEggGroups {
  egg_group_id: number;
  form_id: number;
}

export interface FormOverrides {
  base_friendship: number | null;
  base_scale: number | null;
  catch_rate: number | null;
  egg_cycles: number | null;
  form_id: number;
  male_ratio: number | null;
}

export interface Forms {
  base_attack: number;
  base_defence: number;
  base_experience_yield: number | null;
  base_hp: number;
  base_special_attack: number;
  base_special_defence: number;
  base_speed: number;
  description: string | null;
  ev_attack: Generated<number>;
  ev_defence: Generated<number>;
  ev_hp: Generated<number>;
  ev_special_attack: Generated<number>;
  ev_special_defence: Generated<number>;
  ev_speed: Generated<number>;
  form_name: string;
  generation: number | null;
  height: number;
  id: number;
  name: string;
  slug: string;
  species_id: number;
  weight: number;
}

export interface FormTags {
  form_id: number;
  id: Generated<number>;
  tag_id: number;
}

export interface FormTagTypes {
  id: number;
  name: string;
  slug: string;
}

export interface FormTypes {
  form_id: number;
  slot: number;
  type_id: number;
}

export interface GmaxMoves {
  move_id: number;
  species_id: number;
}

export interface HiddenPowerIvs {
  atk: number;
  def: number;
  hp: number;
  spa: number;
  spd: number;
  spe: number;
  type_id: number;
}

export interface Images {
  created_at: Generated<Timestamp>;
  file_size: Int8 | null;
  height: number | null;
  id: Generated<string>;
  mime_type: string | null;
  s3_key: string;
  status: Generated<ImageStatus>;
  uploaded_at: Timestamp | null;
  uploaded_by: string | null;
  width: number | null;
}

export interface ItemBoosts {
  item_id: number;
  stages: number;
  stat_id: number;
}

export interface ItemFlags {
  flag_type_id: number;
  item_id: number;
}

export interface ItemFlagTypes {
  id: number;
  name: string;
  slug: string;
}

export interface Items {
  desc: string | null;
  gen: number | null;
  id: number;
  implemented: Generated<boolean>;
  name: string;
  namespace_id: number | null;
  num: number | null;
  short_desc: string | null;
  slug: string;
}

export interface ItemTagHierarchy {
  child_tag_id: number;
  id: number;
  parent_tag_id: number;
}

export interface ItemTags {
  item_id: number;
  tag_id: number;
}

export interface ItemTagTypes {
  id: number;
  name: string;
  slug: string;
}

export interface Jwks {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp | null;
  id: string;
  privateKey: string;
  publicKey: string;
}

export interface Labels {
  id: number;
  name: string;
  slug: string;
}

export interface Lighting {
  light_level: number;
  liquid_glow_mode: string | null;
  species_id: number;
}

export interface MoonPhases {
  id: number;
  name: string;
  slug: string;
}

export interface MoveBoosts {
  id: Generated<number>;
  is_self: boolean;
  move_id: number;
  stages: number;
  stat_id: number;
}

export interface MoveCategories {
  description: string | null;
  id: number;
  name: string;
  slug: string;
}

export interface MoveEffects {
  chance: number;
  condition_id: number | null;
  condition_type_id: number;
  id: Generated<number>;
  is_self: boolean;
  move_id: number;
}

export interface MoveFlags {
  flag_id: number;
  move_id: number;
}

export interface MoveFlagTypes {
  description: string | null;
  id: number;
  name: string;
  slug: string;
}

export interface MoveLearnMethods {
  id: number;
  name: string;
  slug: string;
}

export interface MoveMaxPower {
  max_power: number;
  move_id: number;
}

export interface Moves {
  accuracy: number | null;
  category_id: number;
  crit_ratio: number | null;
  desc: string | null;
  drain_percent: number | null;
  heal_percent: number | null;
  id: number;
  max_hits: number | null;
  min_hits: number | null;
  name: string;
  power: number | null;
  pp: number;
  priority: Generated<number>;
  recoil_percent: number | null;
  short_desc: string | null;
  slug: string;
  target_id: number | null;
  type_id: number;
}

export interface MoveTargets {
  description: string | null;
  id: number;
  name: string;
  slug: string;
}

export interface MoveZData {
  is_z_exclusive: Generated<boolean>;
  move_id: number;
  z_crystal: string | null;
  z_effect: string | null;
  z_power: number | null;
}

export interface Namespaces {
  id: number;
  name: string;
  slug: string;
}

export interface Natures {
  id: number;
  minus_stat_id: number | null;
  name: string;
  plus_stat_id: number | null;
  slug: string;
}

export interface OutboxEvents {
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  id: Generated<number>;
  operation: string;
  processed_at: Timestamp | null;
}

export interface RecipeInputs {
  item_id: number;
  recipe_id: number;
  slot: number | null;
  slot_type_id: number | null;
}

export interface Recipes {
  cooking_time: number | null;
  experience: number | null;
  id: number;
  result_count: Generated<number>;
  result_item_id: number | null;
  type_id: number;
}

export interface RecipeSlotTypes {
  description: string | null;
  id: number;
  name: string;
  slug: string;
}

export interface RecipeTagInputs {
  recipe_id: number;
  slot: number | null;
  slot_type_id: number | null;
  tag_id: number;
}

export interface RecipeTagTypes {
  id: number;
  name: string;
  slug: string;
}

export interface RecipeTypes {
  id: number;
  name: string;
  slug: string;
}

export interface Riding {
  data: Json;
  species_id: number;
}

export interface SpawnBuckets {
  id: number;
  name: string;
  slug: string;
}

export interface SpawnConditionBiomes {
  biome_id: number;
  condition_id: number;
}

export interface SpawnConditionBiomeTags {
  biome_tag_id: number;
  condition_id: number;
}

export interface SpawnConditionLure {
  condition_id: number;
  max_lure_level: number | null;
  min_lure_level: number | null;
}

export interface SpawnConditionMoonPhases {
  condition_id: number;
  moon_phase_id: number;
}

export interface SpawnConditionPosition {
  condition_id: number;
  max_y: number | null;
  min_y: number | null;
}

export interface SpawnConditions {
  condition_type: string;
  id: number;
  multiplier: number | null;
  spawn_id: number;
}

export interface SpawnConditionSky {
  can_see_sky: boolean | null;
  condition_id: number;
  max_sky_light: number | null;
  min_sky_light: number | null;
}

export interface SpawnConditionTime {
  condition_id: number;
  time_range_id: number;
}

export interface SpawnConditionTypes {
  id: number;
  name: string;
  slug: string;
}

export interface SpawnConditionWeather {
  condition_id: number;
  is_raining: boolean | null;
  is_thundering: boolean | null;
}

export interface SpawnPositionTypes {
  id: number;
  name: string;
  slug: string;
}

export interface SpawnPresets {
  preset_type_id: number;
  spawn_id: number;
}

export interface SpawnPresetTypes {
  id: number;
  name: string;
  slug: string;
}

export interface Spawns {
  bucket_id: number;
  form_id: number;
  id: number;
  level_max: number;
  level_min: number;
  position_type_id: number;
  weight: number;
}

export interface Species {
  base_friendship: number;
  base_scale: number | null;
  catch_rate: number;
  description: string | null;
  egg_cycles: number;
  experience_group_id: number | null;
  generation: number;
  id: number;
  male_ratio: number | null;
  name: string;
  slug: string;
}

export interface SpeciesEggGroups {
  egg_group_id: number;
  species_id: number;
}

export interface SpeciesHitboxes {
  fixed: Generated<boolean>;
  height: number;
  species_id: number;
  width: number;
}

export interface SpeciesImages {
  created_at: Generated<Timestamp>;
  image_id: string;
  is_primary: Generated<boolean>;
  sort_order: Generated<number>;
  species_id: number;
}

export interface Stats {
  id: number;
  name: string;
  slug: string;
}

export interface TimeRanges {
  id: number;
  name: string;
  slug: string;
}

export interface TypeMatchups {
  attacking_type_id: number;
  defending_type_id: number;
  multiplier: number;
}

export interface Types {
  id: number;
  name: string;
  slug: string;
}

export interface User {
  banExpires: Timestamp | null;
  banned: Generated<boolean | null>;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: Generated<boolean>;
  id: string;
  image: string | null;
  name: string;
  role: Generated<string | null>;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  abilities: Abilities;
  ability_flag_types: AbilityFlagTypes;
  ability_flags: AbilityFlags;
  ability_slots: AbilitySlots;
  account: Account;
  article_categories: ArticleCategories;
  article_category_map: ArticleCategoryMap;
  article_images: ArticleImages;
  articles: Articles;
  aspect_choices: AspectChoices;
  aspect_groups: AspectGroups;
  aspect_groups_map: AspectGroupsMap;
  aspect_types: AspectTypes;
  aspects: Aspects;
  behaviour: Behaviour;
  biome_tag_biomes: BiomeTagBiomes;
  biome_tags: BiomeTags;
  biomes: Biomes;
  condition_types: ConditionTypes;
  conditions: Conditions;
  drop_percentages: DropPercentages;
  drop_ranges: DropRanges;
  egg_groups: EggGroups;
  experience_groups: ExperienceGroups;
  form_abilities: FormAbilities;
  form_aspect_combo_aspects: FormAspectComboAspects;
  form_aspect_combos: FormAspectCombos;
  form_aspects: FormAspects;
  form_drops: FormDrops;
  form_hitboxes: FormHitboxes;
  form_images: FormImages;
  form_labels: FormLabels;
  form_moves: FormMoves;
  form_override_egg_groups: FormOverrideEggGroups;
  form_overrides: FormOverrides;
  form_tag_types: FormTagTypes;
  form_tags: FormTags;
  form_types: FormTypes;
  forms: Forms;
  gmax_moves: GmaxMoves;
  hidden_power_ivs: HiddenPowerIvs;
  images: Images;
  item_boosts: ItemBoosts;
  item_flag_types: ItemFlagTypes;
  item_flags: ItemFlags;
  item_tag_hierarchy: ItemTagHierarchy;
  item_tag_types: ItemTagTypes;
  item_tags: ItemTags;
  items: Items;
  jwks: Jwks;
  labels: Labels;
  lighting: Lighting;
  moon_phases: MoonPhases;
  move_boosts: MoveBoosts;
  move_categories: MoveCategories;
  move_effects: MoveEffects;
  move_flag_types: MoveFlagTypes;
  move_flags: MoveFlags;
  move_learn_methods: MoveLearnMethods;
  move_max_power: MoveMaxPower;
  move_targets: MoveTargets;
  move_z_data: MoveZData;
  moves: Moves;
  namespaces: Namespaces;
  natures: Natures;
  outbox_events: OutboxEvents;
  recipe_inputs: RecipeInputs;
  recipe_slot_types: RecipeSlotTypes;
  recipe_tag_inputs: RecipeTagInputs;
  recipe_tag_types: RecipeTagTypes;
  recipe_types: RecipeTypes;
  recipes: Recipes;
  riding: Riding;
  spawn_buckets: SpawnBuckets;
  spawn_condition_biome_tags: SpawnConditionBiomeTags;
  spawn_condition_biomes: SpawnConditionBiomes;
  spawn_condition_lure: SpawnConditionLure;
  spawn_condition_moon_phases: SpawnConditionMoonPhases;
  spawn_condition_position: SpawnConditionPosition;
  spawn_condition_sky: SpawnConditionSky;
  spawn_condition_time: SpawnConditionTime;
  spawn_condition_types: SpawnConditionTypes;
  spawn_condition_weather: SpawnConditionWeather;
  spawn_conditions: SpawnConditions;
  spawn_position_types: SpawnPositionTypes;
  spawn_preset_types: SpawnPresetTypes;
  spawn_presets: SpawnPresets;
  spawns: Spawns;
  species: Species;
  species_egg_groups: SpeciesEggGroups;
  species_hitboxes: SpeciesHitboxes;
  species_images: SpeciesImages;
  stats: Stats;
  time_ranges: TimeRanges;
  type_matchups: TypeMatchups;
  types: Types;
  user: User;
  verification: Verification;
}
