/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Abilities {
  desc: string | null;
  id: number;
  name: string;
  short_desc: string | null;
  slug: string;
}

export interface AbilityFlags {
  ability_id: number;
  flag_id: number;
}

export interface AbilityFlagTypes {
  description: string | null;
  id: number;
  name: string;
  slug: string;
}

export interface ArticleCategories {
  description: string | null;
  id: Generated<number>;
  name: string;
  slug: string;
}

export interface ArticleCategoryMap {
  article_id: number;
  category_id: number;
}

export interface Articles {
  author: string | null;
  body: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<number>;
  identifier: string;
  subtitle: string | null;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface AspectChoices {
  aspect_id: number;
  aspect_string: string;
  id: number;
  name: string;
  slug: string;
}

export interface AspectGroups {
  description: string | null;
  id: number;
  name: string;
  rule: string;
  slug: string;
}

export interface AspectGroupsMap {
  aspect_group_id: number;
  aspect_id: number;
}

export interface Aspects {
  id: number;
  name: string;
  slug: string;
  type: string;
}

export interface Behaviour {
  data: Json;
  form_id: number;
}

export interface Conditions {
  description: string | null;
  id: number;
  name: string;
  type: string;
}

export interface DropItems {
  id: string;
  source: string;
}

export interface DropPercentages {
  form_id: number;
  id: Generated<number>;
  item_id: string;
  percentage: number;
}

export interface DropRanges {
  form_id: number;
  id: Generated<number>;
  item_id: string;
  quantity_max: number;
  quantity_min: number;
}

export interface EffectTypes {
  id: number;
  name: string;
}

export interface EggGroups {
  id: number;
  name: string;
}

export interface ExperienceGroups {
  formula: string;
  id: number;
  name: string;
}

export interface FormAbilities {
  ability_id: number;
  form_id: number;
  slot: string;
}

export interface FormAspectComboAspects {
  aspect_id: number;
  combo_id: number;
}

export interface FormAspectCombos {
  combo_index: number;
  form_id: number;
  id: Generated<number>;
}

export interface FormAspects {
  aspect_choice_id: number;
  form_id: number;
}

export interface FormDrops {
  amount: number;
  form_id: number;
}

export interface FormHitboxes {
  fixed: Generated<boolean>;
  form_id: number;
  height: number;
  width: number;
}

export interface FormLabels {
  form_id: number;
  label_id: number;
}

export interface FormMoves {
  form_id: number;
  level: number | null;
  method: string;
  move_id: number;
}

export interface FormOverrideEggGroups {
  egg_group_id: number;
  form_id: number;
}

export interface FormOverrides {
  base_friendship: number | null;
  base_scale: number | null;
  catch_rate: number | null;
  egg_cycles: number | null;
  form_id: number;
  male_ratio: number | null;
}

export interface Forms {
  base_attack: number;
  base_defence: number;
  base_experience_yield: number | null;
  base_hp: number;
  base_special_attack: number;
  base_special_defence: number;
  base_speed: number;
  description: string | null;
  ev_attack: number | null;
  ev_defence: number | null;
  ev_hp: number | null;
  ev_special_attack: number | null;
  ev_special_defence: number | null;
  ev_speed: number | null;
  full_name: string;
  generation: number | null;
  height: number;
  id: number;
  name: string;
  slug: string;
  species_id: number;
  weight: number;
}

export interface FormTags {
  form_id: number;
  tag: string;
}

export interface FormTypes {
  form_id: number;
  slot: number;
  type_id: number;
}

export interface GmaxMoves {
  move_id: number;
  species_id: number;
}

export interface HiddenPowerIvs {
  atk: number;
  def: number;
  hp: number;
  spa: number;
  spd: number;
  spe: number;
  type_id: number;
}

export interface ItemBoosts {
  item_id: string;
  stages: number;
  stat_id: number;
}

export interface ItemFlags {
  flag: string;
  item_id: string;
}

export interface Items {
  desc: string | null;
  fling_effect: string | null;
  fling_power: number | null;
  gen: number | null;
  id: string;
  implemented: Generated<boolean>;
  name: string;
  natural_gift_power: number | null;
  natural_gift_type_id: number | null;
  short_desc: string | null;
  source: string;
}

export interface ItemTags {
  item_id: string;
  namespace: string;
  tag: string;
}

export interface Labels {
  id: number;
  name: string;
  slug: string;
}

export interface MoveBoosts {
  id: Generated<number>;
  is_self: boolean;
  move_id: number;
  stages: number;
  stat_id: number;
}

export interface MoveCategories {
  description: string | null;
  id: number;
  name: string;
}

export interface MoveEffects {
  chance: number;
  condition_id: number | null;
  effect_type_id: number;
  id: Generated<number>;
  is_self: boolean;
  move_id: number;
}

export interface MoveFlags {
  flag_id: number;
  move_id: number;
}

export interface MoveFlagTypes {
  description: string | null;
  id: number;
  name: string;
  slug: string;
}

export interface MoveMaxPower {
  max_power: number;
  move_id: number;
}

export interface Moves {
  accuracy: number | null;
  category_id: number;
  crit_ratio: number | null;
  desc: string | null;
  drain_percent: number | null;
  heal_percent: number | null;
  id: number;
  max_hits: number | null;
  min_hits: number | null;
  name: string;
  power: number | null;
  pp: number;
  priority: Generated<number>;
  recoil_percent: number | null;
  short_desc: string | null;
  slug: string;
  target_id: number | null;
  type_id: number;
}

export interface MoveTargets {
  description: string | null;
  id: number;
  name: string;
  slug: string;
}

export interface MoveZData {
  is_z_exclusive: Generated<boolean>;
  move_id: number;
  z_crystal: string | null;
  z_effect: string | null;
  z_power: number | null;
}

export interface Natures {
  id: number;
  minus_stat_id: number | null;
  name: string;
  plus_stat_id: number | null;
  slug: string;
}

export interface OutboxEvents {
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  id: Generated<number>;
  operation: string;
  processed_at: Timestamp | null;
}

export interface RecipeInputs {
  id: Generated<number>;
  input_namespace: string;
  input_type: string;
  input_value: string;
  recipe_id: string;
  slot: number | null;
  slot_type_id: number | null;
}

export interface Recipes {
  id: string;
  result_count: Generated<number>;
  result_id: string;
  type: string;
}

export interface RecipeSlotTypes {
  description: string | null;
  id: number;
  name: string;
}

export interface Species {
  base_friendship: number;
  base_scale: number | null;
  catch_rate: number;
  description: string | null;
  egg_cycles: number;
  experience_group_id: number | null;
  generation: number;
  id: number;
  male_ratio: number | null;
  name: string;
  slug: string;
}

export interface SpeciesEggGroups {
  egg_group_id: number;
  species_id: number;
}

export interface SpeciesHitboxes {
  fixed: Generated<boolean>;
  height: number;
  species_id: number;
  width: number;
}

export interface SpeciesLighting {
  light_level: number;
  liquid_glow_mode: string | null;
  species_id: number;
}

export interface SpeciesRiding {
  data: Json;
  species_id: number;
}

export interface Stats {
  id: number;
  name: string;
}

export interface TagHierarchy {
  child_tag: string;
  parent_tag: string;
}

export interface TypeMatchups {
  attacking_type_id: number;
  defending_type_id: number;
  multiplier: number;
}

export interface Types {
  id: number;
  name: string;
  slug: string;
}

export interface DB {
  abilities: Abilities;
  ability_flag_types: AbilityFlagTypes;
  ability_flags: AbilityFlags;
  article_categories: ArticleCategories;
  article_category_map: ArticleCategoryMap;
  articles: Articles;
  aspect_choices: AspectChoices;
  aspect_groups: AspectGroups;
  aspect_groups_map: AspectGroupsMap;
  aspects: Aspects;
  behaviour: Behaviour;
  conditions: Conditions;
  drop_items: DropItems;
  drop_percentages: DropPercentages;
  drop_ranges: DropRanges;
  effect_types: EffectTypes;
  egg_groups: EggGroups;
  experience_groups: ExperienceGroups;
  form_abilities: FormAbilities;
  form_aspect_combo_aspects: FormAspectComboAspects;
  form_aspect_combos: FormAspectCombos;
  form_aspects: FormAspects;
  form_drops: FormDrops;
  form_hitboxes: FormHitboxes;
  form_labels: FormLabels;
  form_moves: FormMoves;
  form_override_egg_groups: FormOverrideEggGroups;
  form_overrides: FormOverrides;
  form_tags: FormTags;
  form_types: FormTypes;
  forms: Forms;
  gmax_moves: GmaxMoves;
  hidden_power_ivs: HiddenPowerIvs;
  item_boosts: ItemBoosts;
  item_flags: ItemFlags;
  item_tags: ItemTags;
  items: Items;
  labels: Labels;
  move_boosts: MoveBoosts;
  move_categories: MoveCategories;
  move_effects: MoveEffects;
  move_flag_types: MoveFlagTypes;
  move_flags: MoveFlags;
  move_max_power: MoveMaxPower;
  move_targets: MoveTargets;
  move_z_data: MoveZData;
  moves: Moves;
  natures: Natures;
  outbox_events: OutboxEvents;
  recipe_inputs: RecipeInputs;
  recipe_slot_types: RecipeSlotTypes;
  recipes: Recipes;
  species: Species;
  species_egg_groups: SpeciesEggGroups;
  species_hitboxes: SpeciesHitboxes;
  species_lighting: SpeciesLighting;
  species_riding: SpeciesRiding;
  stats: Stats;
  tag_hierarchy: TagHierarchy;
  type_matchups: TypeMatchups;
  types: Types;
}
